load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Download the rules_docker repository at release v0.7.0
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "aed1c249d4ec8f703edddf35cbe9dfaca0b5f5ea6e4cd9e83e99f3b0d1136c3d",
    strip_prefix = "rules_docker-0.7.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.7.0.tar.gz"],
)

# This is NOT needed when going through the language lang_image
# "repositories" function(s).
load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
container_repositories()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
  name = "java_base",
  registry = "gcr.io",
  repository = "distroless/java",
  # 'tag' is also supported, but digest is encouraged for reproducibility.
  digest = "sha256:b2a1413a48ba78568126ed514416db0c92db4d1635ce78125d6f5932d9e1f813",
)


#----------------------------


http_archive(
    name = "startupos",
    sha256 = "abb9cef989265622273d504376a17d7f7ba4f89afd26405ac61e251248efc588",
    strip_prefix = "startup-os-bb205ed849a51122cc09c663e2bab153e4319d60",
    urls = ["https://github.com/google/startup-os/archive/bb205ed849a51122cc09c663e2bab153e4319d60.tar.gz"],
)

http_archive(
    name = "startupos_binaries",
    strip_prefix = "startupos-binaries-76819481d60ad379ea1b4890998cd3bb4554e20c",
    urls = ["https://github.com/oferb/startupos-binaries/archive/76819481d60ad379ea1b4890998cd3bb4554e20c.tar.gz"],
)

load("//third_party/maven:workspace.bzl", "maven_dependencies")
maven_dependencies()



